### ISSUE TITLE
[ERROR] Unable convert

### ISSUE THREAD

**Issue by leovarmak** [sethvincent/ebook-convert#4]
![image](https://user-images.githubusercontent.com/14135553/30032665-dfa876ea-91b4-11e7-9f5b-de05e24c867d.png)

I have installed and added ebook-covert to my dependencies as well

Here is my code 

```javascript
var path = require('path')
var xtend = require('xtend')
var convert = require('ebook-convert')
 
// see more options at https://manual.calibre-ebook.com/generated/en/ebook-convert.html 
var options = {
  input: path.join(__dirname, 'Downloads', 'example.html'),
  output: path.join(__dirname, 'Downloads', 'example.epub'),
}
 
/*
* create epub file
*/
convert(options, function (err) {
  if (err) console.log(err)
})
```

**Comment by Merovex** [comment]
Dude, the problem is ebook-convert is not in your $PATH. This is addressed in the Calibre repo... 

add `/Applications/calibre.app/Contents/MacOS` to your path

**Comment by hungdev** [comment]
@MerovexI get the same error. Your mean is add this line `export PATH=~/Applications/calibre.app/Contents/MacOS/:$PATH` to `.profile` file?

**Comment by Merovex** [comment]
@hungdev that should do it. But, first confirm the path I provide links you to the app.
